### ISSUE TITLE
Python API - UNWINDing arrays that contain None makes server shut down

### ISSUE THREAD

**Issue by flpgrz** [RedisGraph/RedisGraph#1296]
_Redis v6.0.6
RedisGraph v2.0.15_

Hi all,
This might be an already known thing, but while using the Python API I noticed the following unexpected behavior. So I thought I'd just report it here.

 ✅ **Good query:** `batch` does **not** contain any None element, no errors happen when executing this query
```
param = {'batch': batch}  # batch = [[head_id, tail_id, prop_1, prop_2], ...]  
cypher_query = 'UNWIND $batch as row ' \
                       'MATCH (head:Node) WHERE head.id = row[0] ' \
                       'MATCH (tail:Node) WHERE tail.id = row[1] ' \
                       'CREATE (head)-[rel:RELATIONSHIP {prop_1:row[2], prop_2:row[3]}]->(tail)' 
redis_graph.query(cypher_query, param)
```

🛑  **Bad query:** I set one of the properties to None in all relationships, this query makes the server shut down! 
```
for i, relationship in enumerate(batch):
    rel[3] = None  # injecting Nones
    batch[i] = rel
param = {'batch': batch}  # batch = [[head_id, tail_id, prop_1, prop_2], ...]  
cypher_query = 'UNWIND $batch as row ' \
                       'MATCH (head:Node) WHERE head.id = row[0] ' \
                       'MATCH (tail:Node) WHERE tail.id = row[1] ' \
                       'CREATE (head)-[rel:RELATIONSHIP {prop_1:row[2], prop_2:row[3]}]->(tail)' 
redis_graph.query(cypher_query, param)  # this makes the server shut down! 
```

**Error:**
```
Traceback (most recent call last):
  File "...\lib\site-packages\redis\connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "...\lib\site-packages\redis\_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "...\lib\site-packages\redis\connection.py", line 567, in connect
    self.on_connect()
  File "...\lib\site-packages\redis\connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "...\lib\site-packages\redis\connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "...\lib\site-packages\redis\connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "...\lib\site-packages\redis\connection.py", line 256, in readline
    self._read_from_socket()
  File "...\lib\site-packages\redis\connection.py", line 223, in _read_from_socket
    (ex.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)
```

**Comment by DvirDukhan** [comment]
@flpgrz Can you attach server logs?
also, can you confirm that I'm right about my analysis:
You are sending an array of arrays (batch) where one array is `null`?
`[[rel0_props_array], [rel1_props_array], [rel2_props_array], null, [rel0_props_array]]`
 so you try to access `null[0]` for example?

**Comment by flpgrz** [comment]
Hello @DvirDukhan,

No, that's not really how batch is structured. I write here an example of a "good" and of  a "bad" `batch`.

**Good batch**
[ ['Berlin', 'Munich', 'highway', 'max_speed_130'],  ['Stuttgart', 'Munich', 'rural_road', 'max_speed_90'], ..., ... ]

**Bad batch** 
[ ['Berlin', 'Munich', 'highway', None],  ['Stuttgart', 'Munich', 'rural_road', None], ..., ... ]

I'll try to search for the server logs, and attach them! Thanks

**Comment by DvirDukhan** [comment]
@flpgrz also please specify the redisgraph version, thanks

**Comment by flpgrz** [comment]
@DvirDukhan  I checkedout and installed the v2.0.15 release

**Comment by swilly22** [comment]
Issue resolved.
