### ISSUE TITLE
Error in query with -ve value

### ISSUE THREAD

**Issue by manoja1** [RedisGraph/RedisGraph#1336]
We have 2 similar queries in our system  

Query 1 executes with no error

`MERGE (n:SI {name:$name}) ON CREATE SET n._created=timestamp(), n._updated=timestamp() ON MATCH SET n._updated=timestamp() SET n.prop_1=$prop1` with bind  values `{name=ad, prop_1=4.294967296E9}`

Query 2 errors out

`MERGE (n:SI {name:$name}) ON CREATE SET n._created=timestamp(), n._updated=timestamp() ON MATCH SET n._updated=timestamp() SET n.prop_2=$prop2` with bind  values `{name=ad, prop_2=-1.0}`

```
Caused by: redis.clients.jedis.exceptions.JedisDataException: errMsg: Invalid input 'h': expected ';', a statement option, a query hint, a clause or a schema command line: 1, column: 1, offset: 0 errCtx: prop_2=-1.0 MERGE (n:SI {name:$name}) ON CREATE SET n._cr... errCtxOffset: 0
        at redis.clients.jedis.Protocol.processError(Protocol.java:132)
        at redis.clients.jedis.Protocol.process(Protocol.java:166)
        at redis.clients.jedis.Protocol.read(Protocol.java:220)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
        at redis.clients.jedis.Connection.getOne(Connection.java:296)
        at redis.clients.jedis.Jedis.sendCommand(Jedis.java:3835)
        at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:52)
```

The query succeeds without any error when I run from redis-cli

`MERGE (n:SI {name:'ad'}) ON CREATE SET n._created=timestamp(), n._updated=timestamp() ON MATCH SET n._updated=timestamp() SET n.prop_2=-1.0`
 
We are running latest version of redisgraph `docker run -p 6379:6379 redislabs/redisgraph:latest`

**Comment by manoja1** [comment]
Is this the same issue as #1331?

**Comment by DvirDukhan** [comment]
Hi @manoja1 
Seems like it is the same issue 
We have a PR on our parser fork for negative parameters which should be merge soon

https://github.com/RedisGraph/libcypher-parser/pull/3

**Comment by manoja1** [comment]
Is this a regression?

**Comment by swilly22** [comment]
Fix merged, @manoja1 please confirm

**Comment by manoja1** [comment]
Verified. thx for the fix.

**Comment by manoja1** [comment]
I verified on `:edge` but it's not ported to master yet. 

Do Bugs get closed even before they are merged in master?

**Comment by jeffreylovitz** [comment]
The `edge` tag is built from the master branch, so the two are actually equivalent. We typically close bugs once they've been merged into master.

The `latest` tag corresponds to the latest versioned release, which lags behind `edge` a bit, as we do not release a new patch version for every bugfix.
