### ISSUE TITLE
Can't use graph commands even though it is running in docker

### ISSUE THREAD

**Issue by banuAndrei99** [RedisGraph/RedisGraph#1449]
I am starting a redisgraph in docker with ```docker run -p 6379:6379 -it --rm redislabs/redisgraph``` and then I try to run a simple python example:
```python
import redis
from redisgraph import Node, Edge, Graph

r = redis.Redis(host='localhost', port=6379)

redis_graph = Graph('social', r)

john = Node(label='person', properties={'name': 'John Doe', 'age': 33, 'gender': 'male', 'status': 'single'})
redis_graph.add_node(john)
redis_graph.commit()
```
and this fails with:
```python
Traceback (most recent call last):
  File "C:/Users/abanu/Projects/tip-stix-benchmark/x.py", line 10, in <module>
    redis_graph.commit()
  File "C:\Users\abanu\AppData\Local\Programs\Python\Python37\lib\site-packages\redisgraph\graph.py", line 95, in commit
    return self.query(query)
  File "C:\Users\abanu\AppData\Local\Programs\Python\Python37\lib\site-packages\redisgraph\graph.py", line 133, in query
    response = self.redis_con.execute_command(*command)
  File "C:\Users\abanu\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "C:\Users\abanu\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\client.py", line 915, in parse_response
    response = connection.read_response()
  File "C:\Users\abanu\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'GRAPH.QUERY'
```

Output of ```docker run -p 6379:6379 -it --rm redislabs/redisgraph```:
```
1:C 23 Nov 2020 09:26:39.649 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 23 Nov 2020 09:26:39.649 # Redis version=6.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 23 Nov 2020 09:26:39.649 # Configuration loaded
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 6.0.5 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 23 Nov 2020 09:26:39.650 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 23 Nov 2020 09:26:39.650 # Server initialized
1:M 23 Nov 2020 09:26:39.650 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 23 Nov 2020 09:26:39.656 * <graph> Graph deletion will be done asynchronously.
1:M 23 Nov 2020 09:26:39.663 * <graph> Thread pool created, using 2 threads.
1:M 23 Nov 2020 09:26:39.663 * <graph> Maximum number of OpenMP threads set to 2
1:M 23 Nov 2020 09:26:39.663 * Module 'graph' loaded from /usr/lib/redis/modules/redisgraph.so
1:M 23 Nov 2020 09:26:39.664 * Ready to accept connections
```
OS: `Microsoft Windows [Version 10.0.18362.1198]`
I am quite confused since this worked just fine for me last week.
I've tried running command from `redis-cli` after the docker was up and the same problem occurred.

It seems to me like the redisgraph module is not loaded since it does not recognize graph commands, but it in docker it says `Module 'graph' loaded from /usr/lib/redis/modules/redisgraph.so`.

**Comment by gkorland** [comment]
Are you sure you're connecting the right server? can you please run https://redis.io/commands/module-list?
```
127.0.0.1:6379> MODULE LIST
1) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 20207
```

**Comment by banuAndrei99** [comment]
Ignore de postgres image plz :D 
```
C:\Users\abanu>docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                          PORTS                    NAMES
8685ad02cd0b        redislabs/redisgraph   "docker-entrypoint.s…"   27 minutes ago      Up 27 minutes                   0.0.0.0:6379->6379/tcp   eloquent_darwin
66921e0908c3        postgres:11-alpine     "docker-entrypoint.s…"   18 hours ago        Restarting (1) 30 seconds ago                            todo-rust_postgres_1

C:\Users\abanu>docker exec -it eloquent_darwin bash
root@8685ad02cd0b:/data# redis-cli
127.0.0.1:6379> MODULE LIST
1) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 20207
127.0.0.1:6379>
```
After running this I am getting more confident that my code doesn't actually connect to the redis server instantiated in the docker...

**Comment by banuAndrei99** [comment]
I figured it out: I had another `redis-server` process running on my computer
I had to go to task manager and kill it and now it connects to the one in the docker
