### ISSUE TITLE
com.redislabs.redisgraph.exceptions.JRedisGraphException is reported when executing the Cypher query containing XOR 

### ISSUE THREAD

**Issue by abc123000111** [RedisGraph/RedisGraph#2066]
Hello, I discovered that when I executed the following Cypher query, a database error occurred:

MATCH (n0) WHERE (n0.k0 > 0 XOR n0.k0 > 0) RETURN n0

Exception in thread "main" com.redislabs.redisgraph.exceptions.JRedisGraphException: redis.clients.jedis.exceptions.JedisDataException: Type mismatch: expected String but was Integer
	at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:59)
	at com.redislabs.redisgraph.impl.api.RedisGraph.sendQuery(RedisGraph.java:68)
	at com.redislabs.redisgraph.impl.api.AbstractRedisGraph.query(AbstractRedisGraph.java:63)
	at RedisGraphExample.main(RedisGraphExample.java:19)
Caused by: redis.clients.jedis.exceptions.JedisDataException: Type mismatch: expected String but was Integer
	at redis.clients.jedis.Protocol.processError(Protocol.java:135)
	at redis.clients.jedis.Protocol.process(Protocol.java:169)
	at redis.clients.jedis.Protocol.read(Protocol.java:223)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
	at redis.clients.jedis.Connection.getOne(Connection.java:330)
	at redis.clients.jedis.Jedis.sendCommand(Jedis.java:4559)
	at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:52)
	... 3 more

But if I executed the following queries, no error occurred. I wonder if it is a bug.

MATCH (n0) WHERE (n0.k0 > 0 OR n0.k0 > 0) RETURN n0
MATCH (n0) WHERE (n0.k0 > 0 AND n0.k0 > 0) RETURN n0
MATCH (n0) WHERE (n0.k0 > 0) RETURN n0

RedisGraph Version: 2.4.11 Docker
Operating System: Windows 11
API: Cypher/Java API

**Comment by abc123000111** [comment]
For example, here is the whole node information in the graph:

Record{values=[Node{labels=[L2], id=0, propertyMap={}}]}
Record{values=[Node{labels=[L4], id=1, propertyMap={k28=Property{name='k28', value=false}}}]}
Record{values=[Node{labels=[L0], id=2, propertyMap={k5=Property{name='k5', value=}}}]}
Record{values=[Node{labels=[L3], id=3, propertyMap={k22=Property{name='k22', value=true}, k21=Property{name='k21', value=-739227143}, k26=Property{name='k26', value=true}, k25=Property{name='k25', value=HqzpFFaPc}}}]}
Record{values=[Node{labels=[L4], id=4, propertyMap={k24=Property{name='k24', value=}, k25=Property{name='k25', value=5bK1w}}}]}
Record{values=[Node{labels=[], id=5, propertyMap={}}]}
Record{values=[Node{labels=[L1], id=6, propertyMap={k23=Property{name='k23', value=-739227143}, k26=Property{name='k26', value=true}}}]}
Record{values=[Node{labels=[L1], id=7, propertyMap={k10=Property{name='k10', value=145888347}, k25=Property{name='k25', value=}}}]}
Record{values=[Node{labels=[L1], id=8, propertyMap={k11=Property{name='k11', value=X}, k13=Property{name='k13', value=true}, k14=Property{name='k14', value=-739227143}}}]}
Record{values=[Node{labels=[L2], id=9, propertyMap={k27=Property{name='k27', value=iJN}, k14=Property{name='k14', value=145888347}, k25=Property{name='k25', value=w5VS}}}]}
Record{values=[Node{labels=[], id=10, propertyMap={}}]}
Record{values=[Node{labels=[L4], id=11, propertyMap={k28=Property{name='k28', value=true}, k24=Property{name='k24', value=2T9m9ueW}}}]}
Record{values=[Node{labels=[], id=12, propertyMap={}}]}
Record{values=[Node{labels=[L0], id=13, propertyMap={k1=Property{name='k1', value=false}, k2=Property{name='k2', value=}, k4=Property{name='k4', value=false}}}]}
Record{values=[Node{labels=[L2], id=14, propertyMap={}}]}
Record{values=[Node{labels=[L4], id=15, propertyMap={k28=Property{name='k28', value=false}}}]}
Record{values=[Node{labels=[L0], id=16, propertyMap={k5=Property{name='k5', value=}}}]}
Record{values=[Node{labels=[L3], id=17, propertyMap={k22=Property{name='k22', value=true}, k21=Property{name='k21', value=-739227143}, k26=Property{name='k26', value=true}, k25=Property{name='k25', value=HqzpFFaPc}}}]}
Record{values=[Node{labels=[L4], id=18, propertyMap={k24=Property{name='k24', value=}, k25=Property{name='k25', value=5bK1w}}}]}
Record{values=[Node{labels=[], id=19, propertyMap={}}]}
Record{values=[Node{labels=[L1], id=20, propertyMap={k23=Property{name='k23', value=-739227143}, k26=Property{name='k26', value=true}}}]}
Record{values=[Node{labels=[L1], id=21, propertyMap={k10=Property{name='k10', value=145888347}, k25=Property{name='k25', value=}}}]}
Record{values=[Node{labels=[L1], id=22, propertyMap={k11=Property{name='k11', value=X}, k13=Property{name='k13', value=true}, k14=Property{name='k14', value=-739227143}}}]}
Record{values=[Node{labels=[L2], id=23, propertyMap={k27=Property{name='k27', value=iJN}, k14=Property{name='k14', value=145888347}, k25=Property{name='k25', value=w5VS}}}]}
Record{values=[Node{labels=[], id=24, propertyMap={}}]}
Record{values=[Node{labels=[L4], id=25, propertyMap={k28=Property{name='k28', value=true}, k24=Property{name='k24', value=2T9m9ueW}}}]}
Record{values=[Node{labels=[], id=26, propertyMap={}}]}
Record{values=[Node{labels=[L0], id=27, propertyMap={k1=Property{name='k1', value=false}, k2=Property{name='k2', value=}, k4=Property{name='k4', value=false}}}]}

if I executed the following query:
MATCH (n2 :L0) WHERE (((n2.k4) >= 0) **XOR** ((n2.k4) >= 0)) RETURN *

A database error occurred:
Exception in thread "main" com.redislabs.redisgraph.exceptions.JRedisGraphException: redis.clients.jedis.exceptions.JedisDataException: Type mismatch: expected Null but was Integer
	at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:59)
	at com.redislabs.redisgraph.impl.api.RedisGraph.sendQuery(RedisGraph.java:68)
	at com.redislabs.redisgraph.impl.api.AbstractRedisGraph.query(AbstractRedisGraph.java:63)
	at RedisGraphExample.main(RedisGraphExample.java:33)
Caused by: redis.clients.jedis.exceptions.JedisDataException: Type mismatch: expected Null but was Integer
	at redis.clients.jedis.Protocol.processError(Protocol.java:135)
	at redis.clients.jedis.Protocol.process(Protocol.java:169)
	at redis.clients.jedis.Protocol.read(Protocol.java:223)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
	at redis.clients.jedis.Connection.getOne(Connection.java:330)
	at redis.clients.jedis.Jedis.sendCommand(Jedis.java:4559)
	at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:52)
	... 3 more

But if I executed the following query (using OR instead of XOR), no error will be occurred:
MATCH (n2 :L0) WHERE (((n2.k4) >= 0) **OR** ((n2.k4) >= 0)) RETURN *
