### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException is reported when executing the Cypher queries.

### ISSUE THREAD

**Issue by abc123000111** [RedisGraph/RedisGraph#2068]
Hello, I discovered that when I executed the queries in the attached java file, an exception occurred:
[redisgraph.zip](https://github.com/RedisGraph/RedisGraph/files/7733405/redisgraph.zip)

**Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.**
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
	at redis.clients.jedis.Protocol.process(Protocol.java:158)
	at redis.clients.jedis.Protocol.read(Protocol.java:223)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
	at redis.clients.jedis.Connection.getOne(Connection.java:330)
	at redis.clients.jedis.Jedis.sendCommand(Jedis.java:4559)
	at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:52)
	at com.redislabs.redisgraph.impl.api.RedisGraph.sendQuery(RedisGraph.java:68)
	at com.redislabs.redisgraph.impl.api.AbstractRedisGraph.query(AbstractRedisGraph.java:63)
	at RedisGraphExample.main(RedisGraphExample.java:32)

But if I comment out some of the queries, no error will be reported. And if these queries do not contain WHERE clauses, no error will be reported. I wonder if it is a bug. Thanks a lot!

RedisGraph Version: 2.4.11 Docker
Operating System: Windows 11
API: Cypher/Java API
JRedisGraph Version: 2.5.1

**Comment by gkorland** [comment]
Moved: https://github.com/RedisGraph/JRedisGraph/issues/136

**Comment by sazzad16** [comment]
@gkorland This is RedisGraph / docker image issue. If we execute following commands (in that order), `redislabs/redisgraph` image crashes without any error report.

```
redis-cli MONITOR
OK
1644990086.928784 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n1) WHERE ('' STARTS WITH 'R') OPTIONAL MATCH (n1) WHERE (-820943854 <> 1516016742) RETURN DISTINCT n1" "--COMPACT"
1644990086.932882 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n1) WHERE ('Exmp2lRHm' STARTS WITH 'CQ40') OPTIONAL MATCH (n1) WHERE (407882822 >= -1790558090) RETURN max(-909436230) AS a0 LIMIT 1" "--COMPACT"
1644990086.933391 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0 :L3), (n1)-[r0 :T4 *..2]-(n2 :L2) WHERE ((n2.k16) < (n2.k18)) MATCH (n3) WHERE ((n0.k20) STARTS WITH 'gDt4ys7F') RETURN max(1949660164) AS a0, (n0.k20) AS a1 ORDER BY a1" "--COMPACT"
1644990086.933879 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE (-1715327539 <> 298274752) OPTIONAL MATCH (n1 :L2) WHERE ((n1.k13) ENDS WITH '') RETURN (n1.k15) AS a0 SKIP 4 LIMIT 0" "--COMPACT"
1644990086.934246 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE (699342859 <= -1964522166) MATCH (n0)<-[r0 :T1 *1..]-(n1) WHERE ('F' STARTS WITH '') RETURN 1" "--COMPACT"
1644990086.934630 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0)-[r0 *]->(n1 :L3) WHERE ((n1.k22) < (n1.k22)) MATCH (n0) WHERE ((n1.k20) ENDS WITH (n1.k24)) RETURN n0" "--COMPACT"
1644990086.935183 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0)-[r0 *1..]->(n1 :L4) WHERE ((n1.k28) CONTAINS '') MATCH (n2)<-[r1 *1..]-(n3 :L4), (n4 :L4)<-[r2 :T3 *..2]-(n5) WHERE ((n1.k28) ENDS WITH '') RETURN 0" "--COMPACT"
1644990086.935799 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE ('t' STARTS WITH 'D') MATCH (n0) WHERE ('' CONTAINS '') RETURN n0" "--COMPACT"
1644990086.936217 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0)-[r0 *..2]-(n1 :L2), (n2) WHERE ((n1.k18) = (n1.k18)) OPTIONAL MATCH (n1), (n3)-[r2 :T2 *..2]-(n4 :L4) WHERE ((n4.k26) <> (n1.k16)) RETURN 1" "--COMPACT"
1644990086.936783 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0)-[r0 *..2]-(n1) WHERE ('A' ENDS WITH 'tKhEcQx') OPTIONAL MATCH (n2)-[r1 *]-(n3 :L1), (n4 :L4) WHERE ((n3.k10) CONTAINS (n4.k28)) RETURN DISTINCT n2, (n4.k25) AS a0" "--COMPACT"
1644990086.937406 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0), (n1)-[r0 :T3 *1..]->(n2) WHERE (-1518863616 <> -1469524435) MATCH (n1), (n3) WHERE (-602397394 >= -1001014969) RETURN min(-1135431009) AS a0, n1" "--COMPACT"
1644990086.937841 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE ('Es' STARTS WITH '') OPTIONAL MATCH (n1) WHERE ('BB' STARTS WITH 'tSJ2zU') RETURN n1 LIMIT 1" "--COMPACT"
1644990086.938191 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE ('YXHEs' CONTAINS 'u6aN') MATCH (n0) WHERE ('D' STARTS WITH 'P') RETURN stDevP(-1194155646) AS a0" "--COMPACT"
1644990086.938591 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE ('' STARTS WITH '') MATCH (n1 :L1) WHERE ((n1.k9) < 1407283771) RETURN max(-261045610) AS a0, n1, (n1.k8) AS a1" "--COMPACT"
1644990086.939094 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE (-984835943 <> 1605231123) MATCH (n1), (n0) WHERE ('wWoHY' ENDS WITH '') RETURN 1" "--COMPACT"
1644990086.939425 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0)-[r0 *1..]->(n1) WHERE ('BexdnBi' STARTS WITH '') MATCH (n2)-[r1 *]-(n3), (n0) WHERE ('uPFqZ' CONTAINS 'YlW') RETURN 0" "--COMPACT"
1644990086.939783 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n1) WHERE (-1164337499 > 2062750810) MATCH (n2 :L1) WHERE ((n2.k11) ENDS WITH '') RETURN min(406428742) AS a0" "--COMPACT"
1644990086.940116 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0 :L3) WHERE ((n0.k22) > (n0.k22)) OPTIONAL MATCH (n1) WHERE ((n0.k24) CONTAINS '9q') RETURN 2" "--COMPACT"
1644990086.940504 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH () WHERE ('' ENDS WITH 'GR') OPTIONAL MATCH (n1) WHERE ('m' ENDS WITH 'MBaKGyNR') RETURN n1" "--COMPACT"
1644990086.940783 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE ('8UOG' STARTS WITH 'Jfnt') MATCH (n0) WHERE (1857509721 <= -511841589) RETURN n0" "--COMPACT"
1644990086.941052 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0), (n1 :L2) WHERE ((n1.k13) STARTS WITH 'qTc') MATCH (n0) WHERE ((n1.k17) >= -1149677332) RETURN 1 SKIP 0" "--COMPACT"
1644990086.941363 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0)-[r0 :T0 *..2]-(n1 :L1) WHERE ((n1.k9) < (n1.k9)) MATCH (n0) WHERE ((n1.k11) CONTAINS (n1.k11)) RETURN DISTINCT n0 SKIP 2" "--COMPACT"
1644990086.943492 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0 :L2), (n1) WHERE ((n0.k18) < (n0.k19)) OPTIONAL MATCH (n0), (n0) WHERE ((n0.k18) < 738209706) RETURN (n0.k14) AS a0 SKIP 5" "--COMPACT"
1644990086.943902 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE ('rVCJ' STARTS WITH 'so') MATCH (n1 :L2) WHERE ((n1.k13) CONTAINS 'oaAaM1h') RETURN min(1917527063) AS a0, (n1.k15) AS a1" "--COMPACT"
1644990086.944229 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0) WHERE ('8zeYCp' ENDS WITH 'z') OPTIONAL MATCH (n1 :L0)<-[r0 *1..]-(n2) WHERE ((n1.k2) <> (n1.k3)) RETURN DISTINCT 3" "--COMPACT"
1644990086.944624 [0 172.17.0.1:33542] "graph.QUERY" "test" "MATCH (n0), (n2) WHERE ('CNu5' CONTAINS 'pSZsieO') MATCH (n3) WHERE ('bhFZP' CONTAINS '') RETURN 2" "--COMPACT"
Error: Server closed the connection
```

**Comment by AviAvni** [comment]
thank the bug
fixed in https://github.com/RedisGraph/RedisGraph/pull/2167 soon to be merged
