### ISSUE TITLE
RedisGraph crashes when executing query

### ISSUE THREAD

**Issue by ddaa2000** [RedisGraph/RedisGraph#2631]
After executing foloowing queries, RedisGraph-2.8.20 docker crashes:

```
CREATE (n0 :L2{id :5})<-[r0 :T2{id :6}]-(n1:L2{id :7})-[r1 :T5{id :8}]->(n2:L5{id :9});
MATCH (n0 { id: 9}) MERGE (n0)<-[r1 :T6{id :116}]-(n1 :L3{id :117});
MATCH (n5 :L3 :L4) OPTIONAL MATCH (n5 :L3)-[r5 :T1]->(n7 :L3), (n8 :L2)<-[r6 :T2]-(n9 :L3 :L5 :L2) RETURN 1;
```

The driver exceptions:
```
--Caused by: gdsmith.exceptions.MustRestartDatabaseException: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
--	at gdsmith.redisGraph.RedisGraphConnection.executeStatementAndGet(RedisGraphConnection.java:64)
--	at gdsmith.composite.CompositeConnection$2.run(CompositeConnection.java:92)
--	... 3 more
--Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
--	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205)
--	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:46)
--	at redis.clients.jedis.Protocol.process(Protocol.java:126)
--	at redis.clients.jedis.Protocol.read(Protocol.java:192)
--	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
--	at redis.clients.jedis.Connection.getOne(Connection.java:298)
--	at redis.clients.jedis.Connection.executeCommand(Connection.java:127)
--	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
--	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:148)
--	at redis.clients.jedis.UnifiedJedis.graphQuery(UnifiedJedis.java:4310)
--	at gdsmith.redisGraph.RedisGraphConnection.executeStatementAndGet(RedisGraphConnection.java:57)
```

The Redis bug report:
```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 10 Oct 2022 13:56:11.933 # Redis 6.2.6 crashed by signal: 11, si_code: 1
1:M 10 Oct 2022 13:56:11.933 # Accessing address: (nil)
1:M 10 Oct 2022 13:56:11.933 # Crashed running the instruction at: 0x7f8866cb1fab

------ STACK TRACE ------
EIP:
/usr/lib/redis/modules/redisgraph.so(AlgebraicExpression_Dest+0xb)[0x7f8866cb1fab]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f88691a9980]
/usr/lib/redis/modules/redisgraph.so(AlgebraicExpression_Dest+0xb)[0x7f8866cb1fab]
/usr/lib/redis/modules/redisgraph.so(optimizeLabelScan+0x1a6)[0x7f8866cd1b76]
/usr/lib/redis/modules/redisgraph.so(optimizePlan+0x21)[0x7f8866cd1c21]
/usr/lib/redis/modules/redisgraph.so(ExecutionPlan_PreparePlan+0x12)[0x7f8866cbf682]
/usr/lib/redis/modules/redisgraph.so(+0x1f481f)[0x7f8866cb881f]
/usr/lib/redis/modules/redisgraph.so(+0x242644)[0x7f8866d06644]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f886919e6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f8868ec761f]

------ REGISTERS ------
1:M 10 Oct 2022 13:56:11.934 # 
RAX:0000000000000000 RBX:0000000000000001
RCX:00007f8838201218 RDX:0000000000000000
RDI:0000000000000000 RSI:00007f8838201858
RBP:00007f8846008270 RSP:00007f886388c3c0
R8 :00007f8838201158 R9 :00007f8838201158
R10:0000000000000006 R11:0000000000000012
R12:0000000000000000 R13:0000000000000000
R14:00007f8846021480 R15:00007f8838201218
RIP:00007f8866cb1fab EFL:0000000000010206
CSGSFS:002b000000000033
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3cf) -> 0000000166cdad96
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3ce) -> 00007f8846000100
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3cd) -> 00007f884600851c
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3cc) -> 00007f886388c440
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3cb) -> 00007f8846021480
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3ca) -> 00007f8846008534
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c9) -> fffffffe4601a1f8
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c8) -> 00007f8838201218
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c7) -> 00007f8846008524
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c6) -> 00007f8868836280
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c5) -> 00007f8866cd1b3c
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c4) -> 00007f8838201218
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c3) -> 00007f8866cd1b76
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c2) -> 00007f8846008270
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c1) -> 00007f8846024380
1:M 10 Oct 2022 13:56:11.934 # (00007f886388c3c0) -> 0000000000000000

------ INFO OUTPUT ------
# Server
redis_version:6.2.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e15697f1a083b6bc
redis_mode:standalone
os:Linux 5.4.0-86-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:7.5.0
process_id:1
process_supervised:no
run_id:426ab03c6da2420e7eb448ecf92f820e0aeb2958
tcp_port:6379
server_time_usec:1665410171932909
uptime_in_seconds:6
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:4465787
executable:/data/redis-server
config_file:
io_threads_active:0

# Clients
connected_clients:1
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:1
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:5715360
used_memory_human:5.45M
used_memory_rss:12230656
used_memory_rss_human:11.66M
used_memory_peak:5715360
used_memory_peak_human:5.45M
used_memory_peak_perc:106.84%
used_memory_overhead:845912
used_memory_startup:845840
used_memory_dataset:4869448
used_memory_dataset_perc:100.00%
allocator_allocated:1100016
allocator_active:1261568
allocator_resident:5275648
total_system_memory:199447633920
total_system_memory_human:185.75G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.15
allocator_frag_bytes:161552
allocator_rss_ratio:4.18
allocator_rss_bytes:4014080
rss_overhead_ratio:2.32
rss_overhead_bytes:6955008
mem_fragmentation_ratio:14.46
mem_fragmentation_bytes:11384816
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:2
rdb_bgsave_in_progress:0
rdb_last_save_time:1665410165
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:2
total_commands_processed:5
instantaneous_ops_per_sec:0
total_net_input_bytes:735
total_net_output_bytes:577
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:8
keyspace_misses:1
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:6
total_writes_processed:5
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:cd17888c65b803f6d40f7a7c921c5eeb38886e80
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.022592
used_cpu_user:0.015689
used_cpu_sys_children:0.000000
used_cpu_user_children:0.002656
used_cpu_sys_main_thread:0.001850
used_cpu_user_main_thread:0.000000

# Modules
module:name=graph,ver=20820,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_graph.QUERY:calls=5,usec=3050,usec_per_call=610.00,rejected_calls=0,failed_calls=0

# Errorstats

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=8 addr=172.18.0.1:52278 laddr=172.18.0.2:6379 fd=10 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=40954 argv-mem=147 obl=0 oll=0 omem=0 tot-mem=61635 events=r cmd=graph.QUERY user=default redir=-1

------ MODULES INFO OUTPUT ------
# graph_executing commands
graph_command:GRAPH.QUERY MATCH (n5 :L3 :L4) OPTIONAL MATCH (n5 :L3)-[r5 :T1]->(n7 :L3), (n8 :L2)<-[r6 :T2]-(n9 :L3 :L5 :L2) RETURN 1

------ FAST MEMORY TEST ------
1:M 10 Oct 2022 13:56:11.935 # main thread terminated
1:M 10 Oct 2022 13:56:11.935 # Bio thread for job type #0 terminated
1:M 10 Oct 2022 13:56:11.935 # Bio thread for job type #1 terminated
1:M 10 Oct 2022 13:56:11.935 # Bio thread for job type #2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: AlgebraicExpression_Dest (base: 0x7f8866cb1fa0)
Module: /usr/lib/redis/modules/redisgraph.so (base 0x7f8866ac4000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7f8866cb1fa0 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
1:M 10 Oct 2022 13:56:11.935 # dump of function (hexdump of 96 bytes):
5553bb010000004883ec08833f02752f8b470883f802744083f808741383f8017411488b0425100000000f0b0f1f400083f301488b4710488b38833f0274d184db488b4718480f4447104883c4085b5dc30f1f800000000084db488b6f107510

=== REDIS BUG REPORT END. Make sure to include from START to END. ===
```

**Comment by LiorKogan** [comment]
@ddaa2000 thank you for reporting this

**Comment by LiorKogan** [comment]
Same crash, minimal example:

```
GRAPH.QUERY g "CREATE (n:N)"
GRAPH.QUERY g "MATCH (n:N) OPTIONAL MATCH (n:Q) RETURN 1"
```

Note: no crash on:
```
GRAPH.QUERY g "MATCH (n:N) OPTIONAL MATCH (q:Q) RETURN 1"
```

**Comment by AviAvni** [comment]
fixed by https://github.com/RedisGraph/RedisGraph/pull/3034
