### ISSUE TITLE
Float overflow throws AssertionError

### ISSUE THREAD

**Issue by llooFlashooll** [RedisGraph/RedisGraph#2931]
We discovered a bug that Float overflow throws AssertionError.

- RedisGraph version: 2.10.4
- Operating system: macOS 13.2.1
- API/Driver: Java

When I run the following query: `MATCH (n:bTUxc_lz) WHERE NOT(((("")+(0.5532025694847107))+(pow(1691617601455687987,-3057687820537006958)))>=((toLower("[A<"))+(round(0.31866908073425293)))) SET n.z = NULL RETURN n.z` is thrown with an exception. I think the float `round(0.31866908073425293)` should be supported, because it's not really quite a long float, and other GraphDBs normally support this. Specially, we trigger this kinds of bugs several times.

### Expected behavior:
No exception should be expected to throw.

### Actual behavior:
A `java.lang.AssertionError` is thrown. And I think this kind of bugs should be fixed.
```
Caused by: redis.clients.jedis.exceptions.JedisDataException: Float overflow '0.5532025694847107'
	at redis.clients.jedis.Protocol.processError(Protocol.java:96)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.processMultiBulkReply(Protocol.java:183)
	at redis.clients.jedis.Protocol.process(Protocol.java:133)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:282)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:287)
	at redis.clients.jedis.TransactionBase.exec(TransactionBase.java:127)
	at redis.clients.jedis.Transaction.exec(Transaction.java:47)
	at ch.cypherchecker.redis.RedisConnection.execute(RedisConnection.java:38)
	at ch.cypherchecker.redis.RedisQuery.execute(RedisQuery.java:35)
	... 3 more
```

### Steps to reproduce:
We are developing a fuzzing technique to test your GraphDB. We **feel sorry** that because the database schema and data values are randomly generated by strings, it will cause **inconvenience** to your reviewing, but we believe the problem does exist.
Following the following graph data generation query, we can reproduce the bugs:
```
CREATE (i:di58skUDl {sc4i:true, r2:0.5468485951423645, Xhw:(-((-(-4825844936163189029))+(+(316880283239392598))))*((+((-7740378939233631670)+(-8690371166015118897)))*(-(+(-477963001867079692)))), un7:-368766134158564381})
CREATE (lu:bTUxc_lz {Uw:(sqrt(abs(0.8073298335075378)))-((sign(4864368937925437981))+((abs(0.1825835108757019))+((-9100548213347766197)%(0.6138160228729248)))), z:abs(floor(0.32496893405914307))}), (L:J {pHt:(((trim(""))+((0.16889846324920654)*(-7382733623582416594)))+(+(-(0.4892471432685852))))<((toJSON(point({ longitude: -112.671023, latitude: 72.379699 })))+((("?")+(0.4295356869697571))+(floor(0.5745647549629211))))}), (L)-[pNs:QC {AiNe:floor(size("M")), Y:"", d11i:true}]->(L) RETURN pNs.Y , L.pHt ORDER BY pNs.d11i DESC , lu.Uw , L LIMIT 2810673302813931651
DROP INDEX ON :bTUxc_lz(z)
DROP INDEX ON :W(PyhvmXo5p)
DROP INDEX ON :s6YEbgqT(cnLio67)
DROP INDEX ON :Ka(skiRzzPO1k)
DROP INDEX ON :QC(Y)
CALL db.idx.fulltext.drop('gu')
CREATE (BUiQN2e00N:di58skUDl {sc4i:true, r2:(ceil(+(0.08665549755096436)))%(toInteger(("")+("o8~FAd"))), Xhw:((size(""))%(toInteger(0.47434139251708984)))*(size(substring("",-892624412562606748,3789683254612781613))), un7:4852707992833678516}), (fhwmKb:di58skUDl {sc4i:true, r2:(ceil((-1765397844868298847)%(0.2163441777229309)))/((abs(0.15633827447891235))/((+(3.5876035690307617E-4))^(round(-924204307988157350)))), Xhw:null}), (xNU:J {pHt:((substring("",560856991941998502,-3686784914192885753))+(replace("e","vm","A5J")))ENDS WITH(((("N")+(0.2122342586517334))+(("r")+("")))+(floor(0.4969989061355591)))}), (V:J {pHt:true}), (Y9:L6l {KP9MZ8zfE:-946623716178814143, Re:point({ longitude: -132.424836, latitude: 20.282565 }), Q9:5845118085622971125}), (fhwmKb)-[zM:QC {Y:"%!", d11i:true}]->(Y9), (fhwmKb)-[iP4YZ:QC {AiNe:toInteger(-(+(0.6327195763587952)))}]->(V), (fhwmKb)-[SFP6ak:W {gYxJWHLNy:point({ longitude: 55.492279, latitude: 22.348365 })}]->(BUiQN2e00N), (Y9)-[y_:gu {GIZJU:""}]->(BUiQN2e00N), (V)-[q:gu {E:(toLower(("s")+(0.11970210075378418)))+(+(((-4314493868537512757)+(114430909733834723))+(-(7701542646241226714)))), GIZJU:trim((("")+(8121495911420333818))+((null)-(2218062189034855298)))}]->(fhwmKb), (V)-[esbC8:W {gYxJWHLNy:point({ longitude: 151.031105, latitude: 60.862895 })}]->(V), (BUiQN2e00N)-[d:QC {Y:"Bk/*)ee"}]->(Y9), (xNU)-[Bab_:gu {GIZJU:(toLower(left("_ssG[G",9150265853481707877)))+(abs(-(0.7294588088989258)))}]->(V), (xNU)-[U2:QC {Y:"9", d11i:((toLower("reA"))+(+((3291823710237011920)%(-3294311116709746066))))ENDS WITH((right("Rp,5",-1747081820415778224))+(floor(0.3766863942146301)))}]->(BUiQN2e00N), (xNU)-[n:W {PyhvmXo5p:point({ longitude: 116.378938, latitude: -89.611632 }), gYxJWHLNy:point({ longitude: 14.907840, latitude: 67.066089 })}]->(xNU) RETURN * ORDER BY Y9.V7I DESC , SFP6ak, iP4YZ.Y , Bab_.GIZJU DESCENDING , d.AiNe DESCENDING , y_.GIZJU , esbC8, BUiQN2e00N, n.gYxJWHLNy DESC , fhwmKb.Xhw DESC , q.GIZJU DESCENDING , zM.Y , V.pHt DESC , U2
CREATE (pMq:Ka {skiRzzPO1k:point({ longitude: -104.896169, latitude: -32.185732 })}), (E:s6YEbgqT {cnLio67:point({ longitude: 170.452165, latitude: -33.664824 }), INei:sqrt(toInteger(null)), K6:point({ longitude: -20.910323, latitude: -72.090719 })}), (E)-[uoK:W {PyhvmXo5p:point({ longitude: 33.331621, latitude: -68.462620 }), HB:false, gYxJWHLNy:point({ longitude: -64.357846, latitude: 25.977375 })}]->(pMq)
CREATE (AvKPEXmpBn:L6l {KP9MZ8zfE:2709926775135395442, Re:point({ longitude: 96.368194, latitude: -64.243600 })}), (matC5RTlG:s6YEbgqT {cnLio67:point({ longitude: -87.400034, latitude: 52.591921 }), K6:point({ longitude: -3.119986, latitude: -61.391036 }), INei:(abs((6100562829558096770)/(0.3267788887023926)))-((-(-(0.25667089223861694)))/(((-3936323206516970916)-(0.025783896446228027))^(-(0.6775556206703186))))}), (A0:bTUxc_lz {Uw:0.8597386479377747}), (matC5RTlG)-[F9fEBPU:QC {AiNe:ceil(floor(4559454435480416564)), Y:((toLower("*A#(U]'^O"))+(toJSON(point({ longitude: 78.346189, latitude: -46.910345 }))))+((+(floor(-1532861989608247729)))+(toInteger(0.1813543438911438))), d11i:false}]->(matC5RTlG), (matC5RTlG)-[mB:gu {GIZJU:"G*A9W^1"}]->(A0), (A0)-[FP:gu {E:"n7}7", x:"{", GIZJU:""}]->(matC5RTlG), (A0)-[m:gu {E:"*k", x:((lTrim("i"))+((("Pwnbfa")+(0.6680962443351746))+(("/WAQs)EID")+(-58539889102825967))))+(round(+(0.9825827479362488))), GIZJU:toJSON(-(sqrt(0.23034155368804932)))}]->(A0)
CREATE (fwfP:J {pHt:false}), (EWrZSbBqTL:Ka {skiRzzPO1k:point({ longitude: -43.099479, latitude: -82.864829 })}), (Ia:Ka {skiRzzPO1k:point({ longitude: 8.730176, latitude: -23.170990 })}), (s:s6YEbgqT {cnLio67:point({ longitude: -21.269931, latitude: 64.004223 }), K6:point({ longitude: 107.067773, latitude: -26.062668 })}), (gcR:di58skUDl {r2:0.8696280121803284, sc4i:true, Xhw:2065370322552912791, un7:toInteger(floor(0.45639580488204956))}), (s)-[hHlaWHV:QC {AiNe:2744299029244120316, Y:right((("fF")+(""))+(("I2")+("")),toInteger(0.5076265931129456)), d11i:false}]->(s), (s)-[EDhov:gu {x:""}]->(gcR), (s)-[Zlgj:QC {AiNe:(floor((-3187261621279366708)*(8908446394115209957)))*(sign(-(0.8214944005012512)))}]->(Ia), (s)-[eu5g:W {PyhvmXo5p:point({ longitude: 68.395715, latitude: -31.580020 }), HB:true, gYxJWHLNy:point({ longitude: 65.279998, latitude: -37.558586 })}]->(EWrZSbBqTL), (gcR)-[SVE:W {PyhvmXo5p:point({ longitude: 21.222748, latitude: 21.541802 }), HB:true, gYxJWHLNy:point({ longitude: -59.658908, latitude: 81.848622 })}]->(s), (gcR)-[qH:QC {Y:"Z"}]->(EWrZSbBqTL), (gcR)-[kZZL:gu {E:"S", x:""}]->(fwfP), (Ia)-[NjihvSfx:gu {E:"A<M", x:"", GIZJU:(((("%EhArwmCW")+(-4568972894609556703))+(pow(1122560879211922655,6974413969074636284)))+(replace("C","uI","s+lY")))+((toString(point({ longitude: 85.028802, latitude: 5.627642 })))+(rTrim("")))}]->(gcR), (Ia)-[SvQw2Lo0:gu {E:"5", GIZJU:(left(toLower("MIGLI"),sign(0)))+(toUpper(("")+(0.36702102422714233))), x:(((toLower("9S"))+(-(2854966017323629548)))+((ceil(0.7580030560493469))+(+(0.8773707151412964))))+(((trim("pf~F#p"))+(toInteger(6618480655306044324)))+(toUpper("Xq")))}]->(EWrZSbBqTL), (Ia)-[neqDN:QC {AiNe:-324963660230631192, Y:(replace(toLower("fx>"),rTrim("}"),(">cCfsn")+(-2201780374292206700)))+(floor(sqrt(0.337407648563385))), d11i:false}]->(fwfP), (EWrZSbBqTL)-[hIxa_MA:W {PyhvmXo5p:point({ longitude: -172.601323, latitude: -75.389760 }), gYxJWHLNy:point({ longitude: -67.472037, latitude: -40.599510 })}]->(s), (EWrZSbBqTL)-[lZgjl:QC {AiNe:8233628571613813963, d11i:true}]->(EWrZSbBqTL), (EWrZSbBqTL)-[Zt8:gu {x:replace((("dDuT")+(0.5486286282539368))+(abs(0.08097124099731445)),toJSON(true),substring("B",6782982355522195471,1684531002141545065))}]->(fwfP), (fwfP)-[T:QC {AiNe:6021413954664303297, Y:(lTrim(substring("",6585912984222539378,-315022000280109166)))+(+((+(4104908415203962970))+(pow(-5557474078775430618,5316386566596831204)))), d11i:true}]->(s), (fwfP)-[oiC:W {PyhvmXo5p:point({ longitude: 105.408715, latitude: 54.820815 }), gYxJWHLNy:point({ longitude: -5.706936, latitude: 27.972548 })}]->(EWrZSbBqTL), (fwfP)-[Vt2_:gu {E:(lTrim(("")+(0.5604019165039062)))+(-(-(-(-8616920689823510551)))), GIZJU:(toUpper(toUpper("n#}(")))+(+((-(-3520826361665154677))-(-(-4282871659233145830)))), x:reverse(toJSON(0.8254114985466003))}]->(fwfP) RETURN Vt2_ , SVE.PyhvmXo5p AS yreuqlzhuy , lZgjl.d11i AS LIC , oiC.gYxJWHLNy AS HH4 , fwfP.pHt AS c_ , eu5g.gYxJWHLNy AS I , kZZL.GIZJU AS Q , s , hHlaWHV.d11i , T , qH.Y , neqDN.Y AS NL , SvQw2Lo0.x AS XSq , EWrZSbBqTL.skiRzzPO1k , EDhov.GIZJU AS IL2 , Zt8 ORDER BY Vt2_, SVE, NjihvSfx.E , lZgjl, oiC.PyhvmXo5p DESC , fwfP, hIxa_MA, eu5g.PyhvmXo5p DESC , kZZL, s.K6 DESC , hHlaWHV, Ia, neqDN, Zt8.E , Zlgj LIMIT 5389910130641746154
CREATE (x45:di58skUDl {Xhw:1905902594585631180, un7:-7461904759409043453}), (Q2SrpyK:Ka {skiRzzPO1k:point({ longitude: -116.876557, latitude: -18.336002 })}), (qK:bTUxc_lz {Uw:0.5406343936920166, z:+(-((sign(-6316752657916886117))%(ceil(0.3453974723815918))))}), (deI:J {pHt:(sign(+(-7074916620635817077)))<(sign(abs(-8971986419062478314)))}), (x45)-[pTiMl_:gu {E:"] 99Pu", x:trim((rTrim("C+"))+(toJSON(0.5588291883468628))), GIZJU:"OhjgAb%VS"}]->(Q2SrpyK), (x45)-[qw8gg:gu {E:"gO0k", GIZJU:(right(reverse("+M\n"),sign(0.9597602486610413)))+(((("|eC I")+(4980542720196381131))+(toUpper("{r*44B")))+(toJSON(-1883469700014586530)))}]->(x45), (deI)-[S0:QC {AiNe:floor(((8920449976540331755)%(-7037650353493677189))%(size("D(JzJ"))), d11i:false}]->(deI), (qK)-[aIoTz_qTiN:QC {AiNe:4860121497721143273}]->(Q2SrpyK), (qK)-[HzlSrIgc3:W {HB:true, gYxJWHLNy:point({ longitude: 109.113707, latitude: -82.844249 })}]->(qK)
MATCH (n:L6l) WHERE NOT(((+(0.9694775938987732))+(-(0.23029953241348267))) IS NOT NULL) SET n.KP9MZ8zfE = -(+(abs(4934638085821215749))) RETURN n ORDER BY n.Q9 
CREATE INDEX FOR ()-[n:W]-() ON (n.PyhvmXo5p, n.HB, n.gYxJWHLNy)
CREATE (El:di58skUDl {sc4i:(left(("y")+("0"),-(854046001213329332)))>((substring("jHem)i|)",369081165030746498,-8644707515859523065))+((-(0.8134581446647644))%((0.20309722423553467)%(0.913506269454956)))), Xhw:-1}), (GgSmCA:bTUxc_lz {Uw:0.4142048954963684, z:0.22198474407196045}), (El)-[GmQ:gu {GIZJU:""}]->(GgSmCA)
CREATE (d7M9Mo:bTUxc_lz {Uw:0.763338029384613, z:abs((sqrt(7897661983399542104))-(floor(0.011288046836853027)))}), (c:J {pHt:(((("k_")+("O<4_*&"))+(-(-545325604418436613)))+(rTrim("%"))) IS NOT NULL}), (PqS:bTUxc_lz {Uw:0.1996067762374878, z:+(abs(floor(0.13780921697616577)))}), (lsO:di58skUDl {Xhw:8533948034887384460, un7:toInteger(-(+(2158721325001406617)))}), (c)-[v:QC {AiNe:(toInteger(substring(" 0Gk/Ogo",-3896667521371678455,-5963204774779621803)))+(-(abs(-5220623461953064868)))}]->(lsO), (PqS)-[r:W {PyhvmXo5p:point({ longitude: 46.033546, latitude: 55.227563 }), HB:(((left("Dj}",4679035233568165713))+(substring("",7561705507177435260,828330376554182885)))+((("")+(0.16552406549453735))+(replace("","H/\r|6ft",""))))ENDS WITH(lTrim(("]x")+(4221945339604739452))), gYxJWHLNy:point({ longitude: -3.193069, latitude: 66.871910 })}]->(c), (PqS)-[yn1:W {PyhvmXo5p:point({ longitude: -162.625781, latitude: 42.857081 }), HB:false, gYxJWHLNy:point({ longitude: -31.627794, latitude: 66.175769 })}]->(d7M9Mo), (lsO)-[WF:W {PyhvmXo5p:point({ longitude: -64.182080, latitude: 86.351275 }), HB:((reverse("uE-3nwuj"))+(-(sqrt(1881683597149605603))))CONTAINS(("")+((toInteger(0.010158061981201172))%(abs(-1479664016825842137))))}]->(PqS), (d7M9Mo)-[x:gu {E:substring((lTrim("!_"))+(+(null)),ceil(5535396848292683920),sign(2062014445671161353)), GIZJU:"K!'!cfga", x:reverse((("")+(-8262406074380578646))+(+(0.7766600251197815)))}]->(c), (d7M9Mo)-[Q:gu {E:right((trim("tY/'#1_1"))+(("+Sj&")+(0.9559860229492188)),abs(-1256153018894043666)), GIZJU:"s"}]->(PqS), (d7M9Mo)-[ZwvSJ4J:QC {d11i:((toJSON(0.14502626657485962))+(right("",1210523485294729960)))CONTAINS(toLower(lTrim("F*")))}]->(d7M9Mo)
CREATE (Q:bTUxc_lz {Uw:+((floor(6149729151667497248))-(pow(1573825570053309306,-518522773828524570))), z:0.08504778146743774}), (bzDnq_Utgd:bTUxc_lz {Uw:0.529338002204895}) RETURN * 
```

**Comment by LiorKogan** [comment]
There are two things here - a RedisGraph issue and a potential [Jedis](https://github.com/redis/jedis) issue

Simplified queries:

```
GRAPH.QUERY g "MATCH (n) WHERE 10^-324 > 0 RETURN 0"
(error) Integer overflow '-324'

GRAPH.QUERY g "MATCH (n) WHERE pow(10,-324) > 0 RETURN 0"
(error) Integer overflow '0'

GRAPH.QUERY g "MATCH (n) WHERE 0.5 + pow(10,-324) > 0 RETURN 0"
(error) Float overflow '0.5'
```

RedisGraph issue: All these errors are unexpected.

As for the Jedis client - we should check if the result sent from RedisGraph are valid.

**Comment by sazzad16** [comment]
@LiorKogan The reply is coming from the server (RedisGraph).

**Comment by sazzad16** [comment]
@LiorKogan The error/reply is coming from the server (RedisGraph).

**Comment by LiorKogan** [comment]
@sazzad16 Thanks, yes, the "float overflow" / "integer overflow" in this case is a regression in RedisGraph 2.10, see my note above.

However, there are queries for which this is a valid reply, e.g.,:

```
GRAPH.QUERY g "RETURN 10000000000000000000000"
(error) Integer overflow '10000000000000000000000'
```

Should we expect a `java.lang.AssertionError`?

**Comment by sazzad16** [comment]
> Should we expect a `java.lang.AssertionError`?

@LiorKogan We expect `redis.clients.jedis.exceptions.JedisDataException: Float overflow '0.5532025694847107'` which is happening properly. It is wrapped in `java.lang.AssertionError` in OP's source code/application. Yes, few of sentences in the original post, including the title, are misleading.

**Comment by sazzad16** [comment]
To whom it may concern, https://github.com/redis/jedis/pull/3329
