### ISSUE TITLE
Throw exceptions for FOREACH

### ISSUE THREAD

**Issue by llooFlashooll** [RedisGraph/RedisGraph#2965]
- RedisGraph version: 2.10.9
- Operating system: macOS 13.2.1
- API/Driver: Java

When I run the following query: `MATCH path=(a)-[*]->(b) WHERE ID(a)=3 AND ID(b)=5 FOREACH (rel IN relationships(path) | DELETE rel)` is thrown with an exception.

### Expected behavior:
No exception should be expected to throw.

### Actual behavior:
A `java.lang.AssertionError` is thrown. And report this just in case. So will RedisGraph supports some syntaxes like Neo4j in the future? E.g., the syntax here FOREACH is quite a beneficial syntax.
```
java.lang.AssertionError: MATCH path=(a)-[*]->(b) WHERE ID(a)=3 AND ID(b)=5 FOREACH (rel IN relationships(path) | DELETE rel)
	at ch.cypherchecker.redis.RedisQuery.checkException(RedisQuery.java:63)
	at ch.cypherchecker.redis.RedisQuery.executeAndGet(RedisQuery.java:54)
	at ch.cypherchecker.cypher.oracle.CypherPathOracle.check(CypherPathOracle.java:68)
	at ch.cypherchecker.Main.run(Main.java:144)
	at ch.cypherchecker.Main.main(Main.java:108)
Caused by: redis.clients.jedis.exceptions.JedisDataException: RedisGraph does not currently support FOREACH
	at redis.clients.jedis.Protocol.processError(Protocol.java:96)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.processMultiBulkReply(Protocol.java:183)
	at redis.clients.jedis.Protocol.process(Protocol.java:133)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:282)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:287)
	at redis.clients.jedis.TransactionBase.exec(TransactionBase.java:127)
	at redis.clients.jedis.Transaction.exec(Transaction.java:47)
	at ch.cypherchecker.redis.RedisConnection.execute(RedisConnection.java:38)
	at ch.cypherchecker.redis.RedisQuery.executeAndGet(RedisQuery.java:52)
	... 3 more
```

**Comment by LiorKogan** [comment]
`FOREACH` is supported in RedisGraph 2.12.
RedisGraph 2.12-M01 (milestone version) is expected next week. 
You can already execute this query against the edge branch.
