### ISSUE TITLE
Crash when scalar function `id` takes a `scalar` value

### ISSUE THREAD

**Issue by GnaneshKunal** [RedisGraph/RedisGraph#507]
The following query should result in a syntax error but crashes instead. (Would be better if we fix this for 2.0 first)

Query:
`GRAPH.QUERY cc "MATCH (a)-[t]->(b) RETURN id(1)"`

Assertion:
```
redis-server: /redisgraph/src/arithmetic/arithmetic_expression.c:720: AR_ID: Assertion `SI_TYPE(argv[0]) & (T_NODE | T_EDGE)' failed.
```

Here's the trace for graph 2.0:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f60cac75801 in __GI_abort () at abort.c:79
#2  0x00007f60cac6539a in __assert_fail_base (fmt=0x7f60cadec7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f60c7ae5cf8 "SI_TYPE(argv[0]) & (T_NODE | T_EDGE)", file=file@entry=0x7f60c7ae5b78 "/home/gnanesh_r/self/RedisGraph/src/arithmetic/arithmetic_expression.c", line=line@entry=704, function=function@entry=0x7f60c7ae5e9c <__PRETTY_FUNCTION__.13118> "AR_ID") at assert.c:92
#3  0x00007f60cac65412 in __GI___assert_fail (assertion=0x7f60c7ae5cf8 "SI_TYPE(argv[0]) & (T_NODE | T_EDGE)", file=0x7f60c7ae5b78 "/home/gnanesh_r/self/RedisGraph/src/arithmetic/arithmetic_expression.c", line=704, function=0x7f60c7ae5e9c <__PRETTY_FUNCTION__.13118> "AR_ID") at assert.c:101
#4  0x00007f60c79f6d24 in AR_ID (argv=0x7f60c6663360, argc=1) at /home/gnanesh_r/self/RedisGraph/src/arithmetic/arithmetic_expression.c:704
#5  0x00007f60c79f4d6e in AR_EXP_Evaluate (root=0x7f60c180e090, r=0x7f60c181f090) at /home/gnanesh_r/self/RedisGraph/src/arithmetic/arithmetic_expression.c:135
#6  0x00007f60c7a11af0 in ProjectConsume (opBase=0x7f60b4002440) at /home/gnanesh_r/self/RedisGraph/src/execution_plan/ops/op_project.c:83
#7  0x00007f60c7a24a29 in ResultsConsume (opBase=0x7f60b4002510) at /home/gnanesh_r/self/RedisGraph/src/execution_plan/ops/op_results.c:35
#8  0x00007f60c7a094c7 in ExecutionPlan_Execute (plan=0x7f60b4001890) at /home/gnanesh_r/self/RedisGraph/src/execution_plan/execution_plan.c:700
#9  0x00007f60c7a03867 in _MGraph_Query (args=0x7f60ca815240) at /home/gnanesh_r/self/RedisGraph/src/commands/cmd_query.c:113
#10 0x00007f60c7a7ff51 in thread_do (thread_p=0x55acfc686400) at /home/gnanesh_r/self/RedisGraph/src/util/thpool/thpool.c:337
#11 0x00007f60cb02d6db in start_thread (arg=0x7f60c6665700) at pthread_create.c:463
#12 0x00007f60cad5688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

The bug is present in < 2.0 as well.

Server: 

`docker run -p 6380:6379 redislabs/redisgraph:1.2.2`

Bug Report:
```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 30 May 2019 14:03:26.106 # Redis 5.0.5 crashed by signal: 11
1:M 30 May 2019 14:03:26.106 # Crashed running the instruction at: 0x7f4af6ff5529
1:M 30 May 2019 14:03:26.106 # Accessing address: (nil)
1:M 30 May 2019 14:03:26.106 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(abort+0x269)[0x7f4af6ff5529]

Backtrace:
redis-server *:6379(logStackTrace+0x37)[0x55ec6847d3e7]
redis-server *:6379(sigsegvHandler+0xb0)[0x55ec6847db10]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7f4af73710e0]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x269)[0x7f4af6ff5529]
/lib/x86_64-linux-gnu/libc.so.6(+0x2be67)[0x7f4af6fece67]
/lib/x86_64-linux-gnu/libc.so.6(+0x2bf12)[0x7f4af6fecf12]
/usr/lib/redis/modules/redisgraph.so(+0x61a7f)[0x7f4af4b33a7f]
/usr/lib/redis/modules/redisgraph.so(AR_EXP_Evaluate+0x135)[0x7f4af4b341d5]
/usr/lib/redis/modules/redisgraph.so(ProjectConsume+0xee)[0x7f4af4b4102e]
/usr/lib/redis/modules/redisgraph.so(ResultsConsume+0x1d)[0x7f4af4b40b8d]
/usr/lib/redis/modules/redisgraph.so(ExecutionPlan_Execute+0x26)[0x7f4af4b3aec6]
/usr/lib/redis/modules/redisgraph.so(_MGraph_Query+0x20b)[0x7f4af4b387fb]
/usr/lib/redis/modules/redisgraph.so(+0x81784)[0x7f4af4b53784]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4)[0x7f4af73674a4]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f4af70a9d0f]

------ INFO OUTPUT ------
# Server
redis_version:5.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:7983a619928f1f2d
redis_mode:standalone
os:Linux 4.15.0-50-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.3.0
process_id:1
run_id:a030cf5ba823697f4d30fd405db448456f17bf57
tcp_port:6379
uptime_in_seconds:220
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:15721134
executable:/data/redis-server
config_file:

# Clients
connected_clients:1
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:1

# Memory
used_memory:1839736
used_memory_human:1.75M
used_memory_rss:5881856
used_memory_rss_human:5.61M
used_memory_peak:1839736
used_memory_peak_human:1.75M
used_memory_peak_perc:101.20%
used_memory_overhead:841126
used_memory_startup:791360
used_memory_dataset:998610
used_memory_dataset_perc:95.25%
allocator_allocated:2843344
allocator_active:3543040
allocator_resident:6631424
total_system_memory:16711352320
total_system_memory_human:15.56G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.25
allocator_frag_bytes:699696
allocator_rss_ratio:1.87
allocator_rss_bytes:3088384
rss_overhead_ratio:0.89
rss_overhead_bytes:-749568
mem_fragmentation_ratio:3.39
mem_fragmentation_bytes:4147584
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:49694
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:1
rdb_bgsave_in_progress:0
rdb_last_save_time:1559224786
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:9
instantaneous_ops_per_sec:0
total_net_input_bytes:554
total_net_output_bytes:658
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:6
keyspace_misses:2
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:6e8ea87a0110d55637d2bf3408fefc5a78d9b789
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.357472
used_cpu_user:0.315516
used_cpu_sys_children:0.002887
used_cpu_user_children:0.000588

# Commandstats
cmdstat_module:calls=1,usec=6,usec_per_call=6.00
cmdstat_graph.QUERY:calls=8,usec=1211,usec_per_call=151.38

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=3 addr=172.17.0.1:35668 fd=8 name= age=213 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY

------ REGISTERS ------
1:M 30 May 2019 14:03:26.112 # 
RAX:0000000000000006 RBX:00007f4af7eaf000
RCX:00007f4af6ff3fff RDX:0000000000000000
RDI:0000000000000002 RSI:00007f4af12c8160
RBP:00007f4af4bb8b90 RSP:00007f4af12c8270
R8 :0000000000000000 R9 :00007f4af12c8160
R10:0000000000000008 R11:0000000000000246
R12:00000000000002d0 R13:00007f4af4bb8d22
R14:0000000000000008 R15:0000000000000001
RIP:00007f4af6ff5529 EFL:0000000000010246
CSGSFS:002b000000000033
1:M 30 May 2019 14:03:26.112 # (00007f4af12c827f) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c827e) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c827d) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c827c) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c827b) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c827a) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8279) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8278) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8277) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8276) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8275) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8274) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8273) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8272) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8271) -> 0000000000000000
1:M 30 May 2019 14:03:26.112 # (00007f4af12c8270) -> 0000000000000020

------ FAST MEMORY TEST ------
1:M 30 May 2019 14:03:26.112 # Bio thread for job type #0 terminated
1:M 30 May 2019 14:03:26.113 # Bio thread for job type #1 terminated
1:M 30 May 2019 14:03:26.113 # Bio thread for job type #2 terminated
*** Preparing to test memory region 55ec687b3000 (2252800 bytes)
*** Preparing to test memory region 55ec68f3c000 (241664 bytes)
*** Preparing to test memory region 7f4acc000000 (135168 bytes)
*** Preparing to test memory region 7f4ad4000000 (135168 bytes)
*** Preparing to test memory region 7f4ad8000000 (135168 bytes)
*** Preparing to test memory region 7f4adc000000 (135168 bytes)
*** Preparing to test memory region 7f4ae0000000 (135168 bytes)
*** Preparing to test memory region 7f4ae4000000 (135168 bytes)
*** Preparing to test memory region 7f4aeaa00000 (23212032 bytes)
*** Preparing to test memory region 7f4af0000000 (10485760 bytes)
*** Preparing to test memory region 7f4af0acb000 (8388608 bytes)
*** Preparing to test memory region 7f4af12cc000 (8388608 bytes)
*** Preparing to test memory region 7f4af1acd000 (8388608 bytes)
*** Preparing to test memory region 7f4af22ce000 (8388608 bytes)
*** Preparing to test memory region 7f4af2acf000 (8388608 bytes)
*** Preparing to test memory region 7f4af32d0000 (8388608 bytes)
*** Preparing to test memory region 7f4af3ad1000 (8388608 bytes)
*** Preparing to test memory region 7f4af42d2000 (8388608 bytes)
*** Preparing to test memory region 7f4af4dfc000 (4096 bytes)
*** Preparing to test memory region 7f4af4dfe000 (8388608 bytes)
*** Preparing to test memory region 7f4af55ff000 (8388608 bytes)
*** Preparing to test memory region 7f4af5e00000 (8388608 bytes)
*** Preparing to test memory region 7f4af6600000 (8388608 bytes)
*** Preparing to test memory region 7f4af735c000 (16384 bytes)
*** Preparing to test memory region 7f4af7579000 (16384 bytes)
*** Preparing to test memory region 7f4af7e43000 (438272 bytes)
*** Preparing to test memory region 7f4af7eaf000 (4096 bytes)
*** Preparing to test memory region 7f4af7eb2000 (4096 bytes)
```

**Comment by DvirDukhan** [comment]
#613 fixes this issue. RedisGraph will throw a runtime error for type mismatch.
