### ISSUE TITLE
Redisgraph restarts without crashlog while loading ~2Gb using bulk loader

### ISSUE THREAD

**Issue by renewooller** [RedisGraph/RedisGraph#832]
The redisgraph server restarted towards the end of creating many relationships:

On the bulk loader side:

```
 python3 py/bulk_insert.py "nl-tune-yards:default:graph" --max-buffer-size 1024 --max-token-count 32 --max-token-size 32 -h redisgraph.nightlifr.com -q2 -f '{"song":[3,2,3,3,3,3,3,3,2,2,2,3,3,3,2,3],"SONG_IN_FAVOURITE":[3,3,2,3,2]}' -n
 csvs/song.csv -n csvs/system.csv -n csvs/system_zone.csv -n csvs/favourite.csv  -r csvs/SONG_ON_ZONE.csv -r csvs/SONG_IN_FAVOURITE.csv
song  [####################################]  100%          
113517 nodes created with label 'song'
5607 nodes created with label 'system'
system_zone  [####################################]  100%
6901 nodes created with label 'system_zone'
favourite  [####################################]  100%          
406575 nodes created with label 'favourite'
SONG_ON_ZONE  [###################################-]   97%  00:00:45
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/redis/connection.py", line 177, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/root/.local/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/root/.local/lib/python3.7/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/root/.local/lib/python3.7/site-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/root/.local/lib/python3.7/site-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/root/.local/lib/python3.7/site-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/root/.local/lib/python3.7/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/root/.local/lib/python3.7/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
```

On the redisgraph side:

```
1:C 19 Dec 2019 07:58:42.357 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 19 Dec 2019 07:58:42.357 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 19 Dec 2019 07:58:42.357 # Configuration loaded
1:M 19 Dec 2019 07:58:42.359 * Running mode=standalone, port=6379.
1:M 19 Dec 2019 07:58:42.359 # Server initialized
1:M 19 Dec 2019 07:58:42.405 * <graph> Thread pool created, using 2 threads.
1:M 19 Dec 2019 07:58:42.405 * Module 'graph' loaded from /usr/lib/redis/modules/redisgraph.so
1:M 19 Dec 2019 07:58:42.405 * Ready to accept connections
1:C 20 Dec 2019 04:28:12.537 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 20 Dec 2019 04:28:12.537 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 20 Dec 2019 04:28:12.537 # Configuration loaded
1:M 20 Dec 2019 04:28:12.541 * Running mode=standalone, port=6379.
1:M 20 Dec 2019 04:28:12.541 # Server initialized
1:M 20 Dec 2019 04:28:12.577 * <graph> Thread pool created, using 2 threads.
1:M 20 Dec 2019 04:28:12.577 * Module 'graph' loaded from /usr/lib/redis/modules/redisgraph.so
1:M 20 Dec 2019 04:28:12.577 * Ready to accept connections
```

**Comment by renewooller** [comment]
I found with much smaller limits I could view the data piping into redisgraph via the insight tool:

`python3 py/bulk_insert.py "nl-tune-yards:default:graph" --max-buffer-size=2 --max-token-count=2 --max-token-size=2 -h redisgraph.nightlifr.com -q2 -f '{"song":[3,2,3,3,3,3,3,3,2,2,2,3,3,3,2,3],"SONG_IN_FAVOURITE":[3,3,2,3,2]}' -n csvs
/song.csv -n csvs/system.csv -n csvs/system_zone.csv -n csvs/favourite.csv  -r csvs/SONG_ON_ZONE.csv -r csvs/SONG_IN_FAVOURITE.csv`

However, it still failed at that 97% mark with the SONG_ON_ZONE relationships. There's 3.75 GB on the box, this is running in a container with 3.5GB allocated. Total memory likely got up past 1.2GB before failing based on redis insight overview.

**Comment by jeffreylovitz** [comment]
@renewooller So the crash always occurs at 97% into SONG_ON_ZONE?

The `GRAPH.BULK` command received by the server shouldn't run if the container's at risk of running out of memory, and that kind of failure should be reflected in the server log regardless.

Could there be a line in SONG_ON_ZONE that could cause serialization errors?

To determine whether this is an OOM issue, perhaps you could trim some of the node CSV files for a smaller overall input. Otherwise, if you could provide some sample data, that would be helpful!

**Comment by renewooller** [comment]
I suspect OOM because I found that when the amount of memory available to
the container went from ~3.7 to ~3.6GB, it stopped at 96% instead. I'm on
holidays now, but I'll certainly try that (and using a bigger instance)
when I get back.

Cheers,
Rene

**Comment by jeffreylovitz** [comment]
Oh, that definitely sounds like an OOM crash in that case. It's possible that the OS OOM killer is responsible; I'm not sure if that would cause a crash log.

In any case, I should be able to reproduce this scenario. I'm not sure if there's any solvable issue, though - between the server and the bulk loader itself, it might just be that the peak memory needed during import is more than the container can offer.

**Comment by renewooller** [comment]
yeah OOM, working now there's more memory
