### ISSUE TITLE
unknown command 'GRAPH.QUERY'

### ISSUE THREAD

**Issue by PrathamDogra** [RedisGraph/RedisGraph#948]
loading... of graph
creating entrypoint node
split entrypoint into 2 types of endpoints collection and classes
classes endpoint or accessing classes
accessing every collection in entrypoint
commiting
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    agent = Agent(url)
  File "/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/agent.py", line 31, in __init__
    self.initialize_graph()
  File "/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/agent.py", line 58, in initialize_graph
    self.graph.main(self.entrypoint_url, self.api_doc, True)
  File "/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/redis_core/graph_init.py", line 69, in main
    self.redis_graph.commit()
  File "/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/redisgraph/redisgraph/graph.py", line 96, in commit
    return self.query(query)
  File "/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/redisgraph/redisgraph/graph.py", line 130, in query
    response = self.redis_con.execute_command("GRAPH.QUERY", self.name, q, "--compact")
  File "/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/connection.py", line 752, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'GRAPH.QUERY'
* I am running the docker image **docker run -p 6379:6379 -it --rm redislabs/redisgraph** which is running successfully but when I traverse to the /usr/lib/ I won't find any redis folder.

**Comment by PrathamDogra** [comment]
When I run **redis-server  --loadmodule /usr/lib/redis/modules/redisgraph.so** it gives me the following error.

Module /usr/lib/redis/modules/redisgraph.so failed to load: /usr/lib/redis/modules/redisgraph.so: cannot open shared object file: No such file or directory

**Comment by swilly22** [comment]
Hi @PrathamDogra 
Are you certain `redisgraph.so` is located at `/usr/lib/redis/modules` ?

**Comment by PrathamDogra** [comment]
@swilly22 No it's not, there is no folder named redis inside /usr/lib/ directory

**Comment by swilly22** [comment]
Alright, `--loadmodule` needs to be followed by a path to a module, find out where does redisgraph.so resides and update the path.
`redis-server --loadmodule <PATH_TO_REDISGRAPH.SO>`
